from typing import List, Optional
from pydantic import BaseModel, Field


class WarehouseBase(BaseModel):
    """Base schema with common fields for a warehouse."""

    description: str = Field(..., max_length=255, description="Warehouse description")
    is_active: Optional[bool] = Field(
        default=True,
        description="Indicates whether the warehouse is active (True) or inactive (False)",
    )


class WarehouseCreate(WarehouseBase):
    """Schema for creating warehouses.
    - Includes `description` (required).
    - `is_active` is optional and defaults to `True`.
    """

    pass


class WarehouseUpdate(BaseModel):
    """Schema for partially updating a warehouse.
    - Allows updating the `description` and `is_active` status.
    - No field is required; only sent fields will be updated.
    """

    description: Optional[str] = Field(
        None, max_length=255, description="New description for the warehouse"
    )
    is_active: Optional[bool] = Field(
        None, description="New status for the warehouse (True or False)"
    )


class WarehouseResponse(WarehouseBase):
    """Schema for returning warehouse data.
    - `code`: Unique warehouse ID generated by the database.
    """

    id: int = Field(..., description="Unique warehouse code")

    model_config = {"from_attributes": True}


class PaginatedWarehouseResponse(BaseModel):
    data: List[WarehouseResponse]
    total: int
    limit: int
    offset: int

    model_config = {"from_attributes": True}


class BulkStatusUpdate(BaseModel):
    ids: List[int]
    is_active: bool
